name: Sync Secrets to Azure KeyVault

on:
  workflow_dispatch:

jobs:
  sync-dev:
    runs-on: kube-deploy
    environment: dev
    defaults:
      run:
        shell: bash
    container:
      image: mck-tech-platform-srvs.jfrog.io/kubectl-azure:latest
      credentials:
        username: ${{ secrets.DEV_PORTAL_JFROG_USERNAME }}
        password: ${{ secrets.DEV_PORTAL_JFROG_API_KEY }}
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set secrets from GH to vault
        env:
          VT: mt-openai-chat-app-dev
        run: |
            az keyvault secret set --vault-name $VT --name "REDIS-HOST" --value "${{ secrets.REDIS_HOST }}"
  sync-qa:
    runs-on: kube-deploy
    environment: qa
    defaults:
      run:
        shell: bash
    container:
      image: mck-tech-platform-srvs.jfrog.io/kubectl-azure:latest
      credentials:
        username: ${{ secrets.DEV_PORTAL_JFROG_USERNAME }}
        password: ${{ secrets.DEV_PORTAL_JFROG_API_KEY }}
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set secrets from GH to vault
        env:
          VT: mt-openai-chatapp-qa
        run: |
            az keyvault secret set --vault-name $VT --name "REDIS-HOST" --value "${{ secrets.REDIS_HOST }}"
  sync-prod:
    runs-on: kube-deploy
    environment: prod
    defaults:
      run:
        shell: bash
    container:
      image: mck-tech-platform-srvs.jfrog.io/kubectl-azure:latest
      credentials:
        username: ${{ secrets.DEV_PORTAL_JFROG_USERNAME }}
        password: ${{ secrets.DEV_PORTAL_JFROG_API_KEY }}
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set secrets from GH to vault
        env:
          VT: mt-openai-chat-app-prod
        run: |
            az keyvault secret set --vault-name $VT --name "REDIS-HOST" --value "${{ secrets.REDIS_HOST }}"
