name: Sync Secrets to Azure KeyVault

on:
  workflow_dispatch:

jobs:
  sync-dev:
    runs-on: kube-deploy
    environment: dev
    defaults:
      run:
        shell: bash
    container:
      image: mck-tech-platform-srvs.jfrog.io/kubectl-azure:latest
      credentials:
        username: ${{ secrets.DEV_PORTAL_JFROG_USERNAME }}
        password: ${{ secrets.DEV_PORTAL_JFROG_API_KEY }}
    steps:
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set secrets from GH to vault
        env:
          VT: mt-openai-chat-app-dev
        run: |
            az keyvault secret set --vault-name $VT --name "MULESOFT-OPENAI-CLIENT-ID" --value "${{ secrets.MULESOFT_OPENAI_CLIENT_ID }}"
            az keyvault secret set --vault-name $VT --name "MULESOFT-OPENAI-CLIENT-SECRET" --value "${{ secrets.MULESOFT_OPENAI_CLIENT_SECRET }}"
            az keyvault secret set --vault-name $VT --name "OKTA-CLIENT-ID" --value "${{ secrets.OKTA_CLIENT_ID }}"
            az keyvault secret set --vault-name $VT --name "OKTA-CLIENT-SECRET" --value "${{ secrets.OKTA_CLIENT_SECRET }}"
            az keyvault secret set --vault-name $VT --name "OKTA-ISSUER" --value "${{ secrets.OKTA_ISSUER }}"
            az keyvault secret set --vault-name $VT --name "USON-OKTA-CLIENT-ID" --value "${{ secrets.USON_OKTA_CLIENT_ID }}"
            az keyvault secret set --vault-name $VT --name "USON-OKTA-CLIENT-SECRET" --value "${{ secrets.USON_OKTA_CLIENT_SECRET }}"
            az keyvault secret set --vault-name $VT --name "USON-OKTA-ISSUER" --value "${{ secrets.USON_OKTA_ISSUER }}"
            az keyvault secret set --vault-name $VT --name "EXPRESS-SESSION-SECRET" --value "${{ secrets.EXPRESS_SESSION_SECRET }}"
            az keyvault secret set --vault-name $VT --name "REDIS-HOST" --value "${{ secrets.REDIS_HOST }}"
            az keyvault secret set --vault-name $VT --name "REDIS-KEY" --value "${{ secrets.REDIS_KEY }}"
            az keyvault secret set --vault-name $VT --name "TEST-USER-API-KEY" --value "${{ secrets.TEST_USER_API_KEY }}"
            az keyvault secret set --vault-name $VT --name "APPLICATION-INSIGHTS-CONNECTION-STRING" --value "${{ secrets.APPLICATION_INSIGHTS_CONNECTION_STRING }}"
            az keyvault secret set --vault-name $VT --name "USON-APPLICATION-INSIGHTS-CONNECTION-STRING" --value "${{ secrets.USON_APPLICATION_INSIGHTS_CONNECTION_STRING }}"
  sync-qa:
    runs-on: kube-deploy
    environment: qa
    defaults:
      run:
        shell: bash
    container:
      image: mck-tech-platform-srvs.jfrog.io/kubectl-azure:latest
      credentials:
        username: ${{ secrets.DEV_PORTAL_JFROG_USERNAME }}
        password: ${{ secrets.DEV_PORTAL_JFROG_API_KEY }}
    steps:
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set secrets from GH to vault
        env:
          VT: mt-openai-chatapp-qa
        run: |
            az keyvault secret set --vault-name $VT --name "MULESOFT-OPENAI-CLIENT-ID" --value "${{ secrets.MULESOFT_OPENAI_CLIENT_ID }}"
            az keyvault secret set --vault-name $VT --name "MULESOFT-OPENAI-CLIENT-SECRET" --value "${{ secrets.MULESOFT_OPENAI_CLIENT_SECRET }}"
            az keyvault secret set --vault-name $VT --name "OKTA-CLIENT-ID" --value "${{ secrets.OKTA_CLIENT_ID }}"
            az keyvault secret set --vault-name $VT --name "OKTA-CLIENT-SECRET" --value "${{ secrets.OKTA_CLIENT_SECRET }}"
            az keyvault secret set --vault-name $VT --name "OKTA-ISSUER" --value "${{ secrets.OKTA_ISSUER }}"
            az keyvault secret set --vault-name $VT --name "USON-OKTA-CLIENT-ID" --value "${{ secrets.USON_OKTA_CLIENT_ID }}"
            az keyvault secret set --vault-name $VT --name "USON-OKTA-CLIENT-SECRET" --value "${{ secrets.USON_OKTA_CLIENT_SECRET }}"
            az keyvault secret set --vault-name $VT --name "USON-OKTA-ISSUER" --value "${{ secrets.USON_OKTA_ISSUER }}"
            az keyvault secret set --vault-name $VT --name "EXPRESS-SESSION-SECRET" --value "${{ secrets.EXPRESS_SESSION_SECRET }}"
            az keyvault secret set --vault-name $VT --name "REDIS-HOST" --value "${{ secrets.REDIS_HOST }}"
            az keyvault secret set --vault-name $VT --name "REDIS-KEY" --value "${{ secrets.REDIS_KEY }}"
            az keyvault secret set --vault-name $VT --name "TEST-USER-API-KEY" --value "${{ secrets.TEST_USER_API_KEY }}"
            az keyvault secret set --vault-name $VT --name "APPLICATION-INSIGHTS-CONNECTION-STRING" --value "${{ secrets.APPLICATION_INSIGHTS_CONNECTION_STRING }}"
            az keyvault secret set --vault-name $VT --name "USON-APPLICATION-INSIGHTS-CONNECTION-STRING" --value "${{ secrets.USON_APPLICATION_INSIGHTS_CONNECTION_STRING }}"
  sync-prod:
    runs-on: kube-deploy
    environment: prod
    defaults:
      run:
        shell: bash
    container:
      image: mck-tech-platform-srvs.jfrog.io/kubectl-azure:latest
      credentials:
        username: ${{ secrets.DEV_PORTAL_JFROG_USERNAME }}
        password: ${{ secrets.DEV_PORTAL_JFROG_API_KEY }}
    steps:
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set secrets from GH to vault
        env:
          VT: mt-openai-chat-app-prod
        run: |
            az keyvault secret set --vault-name $VT --name "MULESOFT-OPENAI-CLIENT-ID" --value "${{ secrets.MULESOFT_OPENAI_CLIENT_ID }}"
            az keyvault secret set --vault-name $VT --name "MULESOFT-OPENAI-CLIENT-SECRET" --value "${{ secrets.MULESOFT_OPENAI_CLIENT_SECRET }}"
            az keyvault secret set --vault-name $VT --name "OKTA-CLIENT-ID" --value "${{ secrets.OKTA_CLIENT_ID }}"
            az keyvault secret set --vault-name $VT --name "OKTA-CLIENT-SECRET" --value "${{ secrets.OKTA_CLIENT_SECRET }}"
            az keyvault secret set --vault-name $VT --name "OKTA-ISSUER" --value "${{ secrets.OKTA_ISSUER }}"
            az keyvault secret set --vault-name $VT --name "USON-OKTA-CLIENT-ID" --value "${{ secrets.USON_OKTA_CLIENT_ID }}"
            az keyvault secret set --vault-name $VT --name "USON-OKTA-CLIENT-SECRET" --value "${{ secrets.USON_OKTA_CLIENT_SECRET }}"
            az keyvault secret set --vault-name $VT --name "USON-OKTA-ISSUER" --value "${{ secrets.USON_OKTA_ISSUER }}"
            az keyvault secret set --vault-name $VT --name "EXPRESS-SESSION-SECRET" --value "${{ secrets.EXPRESS_SESSION_SECRET }}"
            az keyvault secret set --vault-name $VT --name "REDIS-HOST" --value "${{ secrets.REDIS_HOST }}"
            az keyvault secret set --vault-name $VT --name "REDIS-KEY" --value "${{ secrets.REDIS_KEY }}"
            az keyvault secret set --vault-name $VT --name "TEST-USER-API-KEY" --value "${{ secrets.TEST_USER_API_KEY }}"
            az keyvault secret set --vault-name $VT --name "APPLICATION-INSIGHTS-CONNECTION-STRING" --value "${{ secrets.APPLICATION_INSIGHTS_CONNECTION_STRING }}"
            az keyvault secret set --vault-name $VT --name "USON-APPLICATION-INSIGHTS-CONNECTION-STRING" --value "${{ secrets.USON_APPLICATION_INSIGHTS_CONNECTION_STRING }}"
